### PR TITLE
Fix typo in Content.jsx

### PR DESCRIPTION
**Pull request by hairychris**
One small change to fix simple typo in types.Content.jsx

### CODE REVIEW

**Comment by jspears** [comment]
Hey thanks for the PR, but looks like the code changed.   hope it didn't break anything of yours.   Content is still a bit, err in flux.     The subschema-g10n module is forcing a few hopefully non-breaking changes...

**Comment by hairychris** [comment]
All good here thanks for asking, it just jumped out at me as I was trying to understand how everything works. This is a really cool library, if I spot anything more useful I'll raise an issue / pull request.

I'm very interested to test how the g10n works, I went for doing it on the server for ease.

**Comment by jspears** [comment]
The G10n plan - doing some thinking here - bear with me.

The idea write your schema in the default locale, but include it with the subschema-g10n-loader.   That will do some transforms to the schema (adding keys to g10n) and extract the content to localization files.   Then when the locale changes it will read the localization files and update the schema.  

It parses ICU so you get pluralization, number formatting, date formatting, currency and so on.  In a format professional translators understand.

My big worry right now is the ICU is parsed on the client (and the server in isomorphic mode).  But I would rather store the intermediate representation.  So I may make the webpack loader do that too.

I am thinking it will have a batch mode that will just convert all schema, and allow for concat to work... So you don't have to recompile all of your app for each locale, just concat the localized schema to the app and should be good to go.   It would create 1 app file per locale.    My work project has ~250 countries to support, so I need the localization to go fast.  The way it is now, takes an hour to generate all the files, and with every new file its taking minutes longer.  I am hoping to get it to < 30s.  

Meeting with the localization team tomorrow to make sure they are kosher with this, if so I hope to have g10n out a bit afterwards.

**Comment by hairychris** [comment]
Sorry I just saw this, sounds like an excellent plan thanks for taking the time to explain it. That's a lot of countries you have to support!

Writing in the default locale sounds sensible. 

I think making the webpack loader store the intermediate representation sounds like a good idea. If I was adding locales I'd be happy to run a build step to avoid having to repeatedly regenerate something at runtime. Even better if you can concat something something into the dist folder though, that sounds great.

I'm watching both subschema-g10n and subschema and I'll try and contribute where I can. Keep up the good work and thanks for open sourcing this.

**Pull request closed without merging**
