### PR TITLE
ENH: updated helper styles

### PR DESCRIPTION
**Pull request by kiranvenkatesh**
Created container for helper and error texts with default styling, including mobile styles

### CODE REVIEW

**Comment by jspears** [comment]
Not ignoring this, but having internal debate about it.   Have tried to keep custom stylings out as much as possible and go with bootstrap defaults.   This is obviously suboptimal.  

What I was thinking about is abstracting all the css, so that it would be much easier to change css frameworks.  I.E. Skeleton, or Foundation.    However this is a lot of work.

I really don't like being bound to a css framework for this.  But it does help out of the boxness of it.


FYI - You can add your own template as the EditorTemplate.jsx 
```js
  loader = require('subschema/loader.jsx');
loader.addTemplate('EditorTemplate', require('./yourtemplate'));

```
This should allow you to use whatever formatting.   

Anyways thanks for the patch!

**Comment by kiranvenkatesh** [comment]
Hey,

No problem. For our project needs we need to sperate the two and I think it is also useful to spearate the two. Rather than loose the helper on error, keeping the helper would help the user resolve the issue faster. 

Thanks for following up and the tip on the template loader. Should make life easier.

**Comment by jspears** [comment]
well, depends on your project setup.
Generally I would think its better to use webpack and require to include the pieces you need.   I haven't written about it but, you can setup your own loader, with just the types, templates, validators you use, so you don't have to include things you don't.  Honestly, the dist script is not something I've ever use, and am surprised it works at all,  someone wanted it so, i just did it.   


To generate a new dist, should just be  a npm run prepublish in the subschema project.
or "webpack --config webpack.config.js -p",

You are correct that help and error should be able to exist at the same time.  I will merge that,

**Comment by jspears** [comment]
Eh, closing this. Sorry I didn't merge,

**Comment by kiranvenkatesh** [comment]
No worries. We are using the loader for a custom template. Thanks!

**Pull request closed without merging**
